// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImapMessages() {
  return window['go']['main']['App']['GetImapMessages']();
}

export function GetMailboxTree() {
  return window['go']['main']['App']['GetMailboxTree']();
}

export function GetMessage(arg1) {
  return window['go']['main']['App']['GetMessage'](arg1);
}

export function LoadMailboxes() {
  return window['go']['main']['App']['LoadMailboxes']();
}
