// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMailboxTree():Promise<string>;

export function GetMessage(arg1:number):Promise<main.GetMessageData>;

export function GetMessageList(arg1:string):Promise<string>;

export function LoadMailboxes():Promise<void>;

export function LoadMessages():Promise<void>;
