// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetImapMessages():Promise<Array<main.Message>>;

export function GetMailboxTree():Promise<string>;

export function GetMessage(arg1:number):Promise<main.Message>;

export function LoadMailboxes():Promise<void>;
